# Book settings
title: Options Hedge
author: Akhil Karra, Zoe Xu, Vivaan Shroff, Wendy Wang
copyright: "2025"
logo: ""
description: "Documentation for the options-hedge package"

# Only build files specified in table of contents
only_build_toc_files: true

# Use pre-executed notebooks (standard practice for long-running analyses)
execute:
  execute_notebooks: 'off'  # Use existing outputs from local execution
  timeout: 600
  run_in_temp: false
  allow_errors: false

# LaTeX settings
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: options-hedge.tex

# Bibliography settings
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons
repository:
  url: https://github.com/cmu-21393-f25-group-D/options-hedge
  path_to_book: docs
  branch: main

# HTML settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  baseurl: https://cmu-21393-f25-group-D.github.io/options-hedge
  favicon: ""
  use_fullscreen_button: true
  extra_navbar: ""
  extra_footer: ""
  analytics:
    google_analytics_id: ""
  comments:
    hypothesis: false
    utterances: false

# Sphinx settings
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx.ext.autosummary
    - sphinx.ext.intersphinx
    - sphinxcontrib.bibtex
    - sphinx_proof
    - sphinx_togglebutton
    - sphinx.ext.mathjax
  config:
    html_theme: quantecon_book_theme
    html_logo: ""
    html_title: "21-393: Operations Research II, Carnegie Mellon University"
    html_theme_options:
      header_organisation: "Options Hedge"
      header_organisation_url: https://cmu-21393-f25-group-D.github.io/options-hedge
      repository_url: https://github.com/cmu-21393-f25-group-D/options-hedge
      nb_repository_url: ""
      description: Documentation for the options-hedge package
      keywords: Python, Finance, Options, Hedging
      launch_buttons:
        notebook_interface: classic
        colab_url: ""
        binderhub_url: ""
        jupyterhub_url: ""
        thebe: false
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    latex_elements:
        preamble: |
          \\usepackage{amsmath,amsfonts,amssymb}
          \\usepackage{mathrsfs}
          \\usepackage{physics}
          \\usepackage{cancel}
